---
kind: Service
apiVersion: v1
metadata:
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    io.kompose.service: mariadb
